### ISSUE TITLE
Error installing RDS

### ISSUE THREAD

**Issue by aguillenv** [iasql/iasql#2079] opened 2023-02-28 15:38 UTC
![Image](https://user-images.githubusercontent.com/5898639/221902601-cdde35f9-cbec-4fb7-9339-fd4c438992ac.png)

**Comment by dfellis** [comment] 2023-02-28 15:51
Our RDS implementation doesn't support Aurora (yet). This is a duplicate of #1121 I think?

**Comment by aguillenv** [comment] 2023-02-28 17:18
but we should not be failing, just ignore it :/

**Comment by dfellis** [comment] 2023-02-28 17:27
> but we should not be failing, just ignore it :/

Oh right, we probably should just drop those values from the `parameter_group_family_enum` even if we have to maintain our own enum for this.

**Closed** 2023-03-06 18:02 UTC
Labels: bug
